import { Product, Category } from './types';

export const WHATSAPP_NUMBER = '5511984773673';
export const PIZZERIA_NAME = 'Pizzaria Lobo';
export const PIZZERIA_SLOGAN = 'Deus é Fiel';
export const PIZZERIA_ADDRESS = 'Rafard, 2010 - casa 40, Carapicuíba/SP';
export const PIZZERIA_ADDRESS_FULL = 'Rafard, 2010 - casa 40, Carapicuíba/SP - CEP 06390-240';
export const PIZZERIA_CITY = 'Carapicuíba';
export const PIZZERIA_MAPS_QUERY = 'Rafard 2010 casa 40, Carapicuíba, SP, 06390-240';
export const PIZZERIA_MAPS_EMBED_URL = `https://maps.google.com/maps?q=${encodeURIComponent(PIZZERIA_MAPS_QUERY)}&t=&z=16&ie=UTF8&iwloc=&output=embed`;
export const PIZZERIA_MAPS_LINK_URL = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(PIZZERIA_MAPS_QUERY)}`;
export const PIZZERIA_MAPS_ROUTE_URL = `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(PIZZERIA_MAPS_QUERY)}`;
export const PIZZERIA_PHONE = '(11) 4202-7760';
export const PIZZERIA_WHATSAPP = '(11) 98477-3673';
export const PIZZERIA_INSTAGRAM = '@Pizzaria_Lobo';
export const PIZZERIA_FACEBOOK = 'Pizzaria Lobo';
export const DELIVERY_FEE = 0;
export const DELIVERY_FEE_TEXT = 'Consultar taxa de entrega';
export const MIN_ORDER = 0;

export const PAYMENT_METHODS = [
  'Visa',
  'Visa Electron',
  'Mastercard',
  'Rede Shop',
  'VR',
  'Ticket',
  'Sodexo',
  'Pix',
];

export const HOURS = {
  mon: '18:00 - 00:00',
  tue: '18:00 - 00:00',
  wed: '18:00 - 00:00',
  thu: '18:00 - 00:00',
  fri: '18:00 - 00:00',
  sat: '18:00 - 00:00',
  sun: '18:00 - 00:00',
};

export const HOURS_TEXT = 'Segunda a Domingo: 18:00 às 00:00';
export const OPENING_MESSAGE = 'Abrimos às Segundas Feiras';

export const PROMO = {
  title: 'Promoção',
  price: 43.0,
  deliveryNote: 'Consultar taxa de entrega',
  flavors: [
    'Calabresa',
    'Mussarela',
    'Misto Quente',
    'Jardineira',
    'Baiana',
    'Romeu e Julieta',
  ],
};

export const CATEGORIES: Category[] = [
  { slug: 'queijo', name: 'Queijos', icon: 'pizza' },
  { slug: 'calabresa', name: 'Calabresa', icon: 'flame' },
  { slug: 'carnes', name: 'Carnes', icon: 'beef' },
  { slug: 'frango', name: 'Frango', icon: 'drumstick' },
  { slug: 'legumes', name: 'Legumes', icon: 'leaf' },
  { slug: 'presunto', name: 'Presunto', icon: 'sandwich' },
  { slug: 'frutos-do-mar', name: 'Frutos do Mar', icon: 'fish' },
  { slug: 'especiais', name: 'Especiais', icon: 'star' },
  { slug: 'doces', name: 'Doces', icon: 'cake' },
  { slug: 'batatas', name: 'Batatas', icon: 'fries' },
  { slug: 'pasteis', name: 'Pastéis', icon: 'pie' },
  { slug: 'bebidas', name: 'Bebidas', icon: 'cup' },
];

const CRUSTS = [
  { name: 'Catupiry', price: 5 },
  { name: 'Cheddar', price: 5 },
  { name: 'Sem borda', price: 0 },
];

function pizzaSizes(priceLarge: number, priceBrotinho: number) {
  return [
    { name: 'Brotinho', price: priceBrotinho },
    { name: 'Grande', price: priceLarge },
  ];
}

export const PRODUCTS: Product[] = [
  // ===================== QUEIJOS =====================
  {
    id: '2',
    name: 'Mussarela',
    description: 'Mussarela, orégano e azeitona',
    price: 43.0,
    priceBrotinho: 28.0,
    image: '/images/Pizzas/Mussarela_43_11zon.webp',
    category: 'queijo',
    ingredients: ['Mussarela', 'Orégano', 'Azeitona'],
    sizes: pizzaSizes(43, 28),
    crusts: CRUSTS,
  },
  {
    id: '3',
    name: 'Napolitana',
    description: 'Tomate, mussarela e parmesão',
    price: 48.0,
    priceBrotinho: 30.0,
    image: '/images/Pizzas/Napolitana_44_11zon.webp',
    category: 'queijo',
    ingredients: ['Tomate', 'Mussarela', 'Parmesão'],
    sizes: pizzaSizes(48, 30),
    crusts: CRUSTS,
  },
  {
    id: '4',
    name: 'Marguerita',
    description: 'Mussarela, tomate e manjericão',
    price: 47.0,
    priceBrotinho: 30.0,
    image: '/images/Pizzas/Marguerita_37_11zon.webp',
    category: 'queijo',
    ingredients: ['Mussarela', 'Tomate', 'Manjericão'],
    sizes: pizzaSizes(47, 30),
    crusts: CRUSTS,
  },
  {
    id: '5',
    name: 'Batata Palha',
    description: 'Mussarela, batata palha e azeitona',
    price: 47.0,
    priceBrotinho: 30.0,
    image: '/images/Pizzas/Batata Palha_5_11zon.webp',
    category: 'queijo',
    ingredients: ['Mussarela', 'Batata Palha', 'Azeitona'],
    sizes: pizzaSizes(47, 30),
    crusts: CRUSTS,
  },
  {
    id: '6',
    name: 'Dois Queijos',
    description: 'Catupiry e mussarela',
    price: 48.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Dois Queijos_25_11zon.webp',
    category: 'queijo',
    ingredients: ['Catupiry', 'Mussarela'],
    sizes: pizzaSizes(48, 31),
    crusts: CRUSTS,
  },
  {
    id: '7',
    name: 'Três Queijos',
    description: 'Catupiry, mussarela e parmesão',
    price: 50.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Três Queijos_57.webp',
    category: 'queijo',
    ingredients: ['Catupiry', 'Mussarela', 'Parmesão'],
    sizes: pizzaSizes(50, 32),
    crusts: CRUSTS,
  },
  {
    id: '8',
    name: 'Quatro Queijos',
    description: 'Provolone, mussarela, catupiry e parmesão',
    price: 52.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Quatro Queijos_53_11zon.webp',
    category: 'queijo',
    ingredients: ['Provolone', 'Mussarela', 'Catupiry', 'Parmesão'],
    sizes: pizzaSizes(52, 33),
    crusts: CRUSTS,
  },
  {
    id: '9',
    name: 'Cinco Queijos',
    description: 'Provolone, mussarela, catupiry, parmesão e cheddar',
    price: 54.0,
    priceBrotinho: 35.0,
    image: '/images/Pizzas/Cinco Queijos_22_11zon.webp',
    category: 'queijo',
    ingredients: ['Provolone', 'Mussarela', 'Catupiry', 'Parmesão', 'Cheddar'],
    sizes: pizzaSizes(54, 35),
    crusts: CRUSTS,
  },

  // ===================== CALABRESA =====================
  {
    id: '10',
    name: 'Calabresa',
    description: 'Calabresa artesanal com cebola e orégano',
    price: 43.0,
    priceBrotinho: 28.0,
    image: '/images/Pizzas/Calabresa_11_11zon.webp',
    category: 'calabresa',
    sizes: pizzaSizes(43, 28),
    crusts: CRUSTS,
  },
  {
    id: '11',
    name: 'Catubresa',
    description: 'Calabresa com catupiry',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Catubresa_17_11zon.webp',
    category: 'calabresa',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },
  {
    id: '12',
    name: 'Brasiliana',
    description: 'Calabresa especial com temperos brasileiros',
    price: 50.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Brasiliana_8_11zon.webp',
    category: 'calabresa',
    sizes: pizzaSizes(50, 32),
    crusts: CRUSTS,
  },
  {
    id: '13',
    name: 'Baiana',
    description: 'Calabresa com pimenta e temperos baianos',
    price: 43.0,
    priceBrotinho: 28.0,
    image: '/images/Pizzas/Baiana_4_11zon.webp',
    category: 'calabresa',
    sizes: pizzaSizes(43, 28),
    crusts: CRUSTS,
  },
  {
    id: '14',
    name: 'Cubana',
    description: 'Calabresa cubana especial',
    price: 51.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Cubana_23_11zon.webp',
    category: 'calabresa',
    sizes: pizzaSizes(51, 33),
    crusts: CRUSTS,
  },
  {
    id: '15',
    name: 'Jardineira',
    description: 'Calabresa com legumes variados',
    price: 43.0,
    priceBrotinho: 28.0,
    image: '/images/Pizzas/Jardineira_32_11zon.webp',
    category: 'calabresa',
    sizes: pizzaSizes(43, 28),
    crusts: CRUSTS,
  },
  {
    id: '16',
    name: 'Toscana',
    description: 'Linguiça toscana com temperos italianos',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Toscana_56_11zon.webp',
    category: 'calabresa',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },

  // ===================== CARNES =====================
  {
    id: '17',
    name: 'Lombinho',
    description: 'Lombinho suíno com temperos especiais',
    price: 48.0,
    priceBrotinho: 29.0,
    image: '/images/Pizzas/Lombinho_34_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(48, 29),
    crusts: CRUSTS,
  },
  {
    id: '18',
    name: 'Aurora',
    description: 'Carne especial com molho aurora',
    price: 48.0,
    priceBrotinho: 29.0,
    image: '/images/Pizzas/Aurora_3_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(48, 29),
    crusts: CRUSTS,
  },
  {
    id: '19',
    name: 'Moda da Casa',
    description: 'Receita exclusiva da Pizzaria Lobo',
    price: 52.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Moda da Casa_41_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(52, 33),
    crusts: CRUSTS,
  },
  {
    id: '20',
    name: 'Veneza',
    description: 'Carne selecionada estilo veneziano',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Veneza_60_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },
  {
    id: '21',
    name: 'Carne Seca I',
    description: 'Carne seca desfiada com temperos',
    price: 55.0,
    priceBrotinho: 35.0,
    image: '/images/Pizzas/Carne Seca I_15_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(55, 35),
    crusts: CRUSTS,
  },
  {
    id: '22',
    name: 'Carne Seca II',
    description: 'Carne seca com catupiry e cebola',
    price: 55.0,
    priceBrotinho: 35.0,
    image: '/images/Pizzas/Carne Seca II_16_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(55, 35),
    crusts: CRUSTS,
  },
  {
    id: '23',
    name: 'Cearense',
    description: 'Carne seca ao estilo cearense',
    price: 57.0,
    priceBrotinho: 35.0,
    image: '/images/Pizzas/Cearense_18_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(57, 35),
    crusts: CRUSTS,
  },
  {
    id: '24',
    name: 'Palestra',
    description: 'Carne moída com temperos especiais',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Palestra_47_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },
  {
    id: '25',
    name: 'Bolonhesa',
    description: 'Molho bolonhesa artesanal',
    price: 51.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Bolonhesa_7_11zon.webp',
    category: 'carnes',
    sizes: pizzaSizes(51, 32),
    crusts: CRUSTS,
  },

  // ===================== FRANGO =====================
  {
    id: '26',
    name: 'Frango I',
    description: 'Frango desfiado com catupiry',
    price: 51.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Frango I_27_11zon.webp',
    category: 'frango',
    sizes: pizzaSizes(51, 33),
    crusts: CRUSTS,
  },
  {
    id: '27',
    name: 'Frango II',
    description: 'Frango desfiado com milho e catupiry',
    price: 52.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Frango II_28_11zon.webp',
    category: 'frango',
    sizes: pizzaSizes(52, 33),
    crusts: CRUSTS,
  },
  {
    id: '28',
    name: 'Franguete',
    description: 'Frango com temperos especiais',
    price: 51.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Franguete_29_11zon.webp',
    category: 'frango',
    sizes: pizzaSizes(51, 33),
    crusts: CRUSTS,
  },
  {
    id: '29',
    name: 'Galinhada',
    description: 'Frango com queijo e temperos caseiros',
    price: 53.0,
    priceBrotinho: 35.0,
    image: '/images/Pizzas/Galinhada_30_11zon.webp',
    category: 'frango',
    sizes: pizzaSizes(53, 35),
    crusts: CRUSTS,
  },
  {
    id: '30',
    name: 'Mexicana',
    description: 'Frango com pimenta e temperos mexicanos',
    price: 52.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Mexicana_38_11zon.webp',
    category: 'frango',
    sizes: pizzaSizes(52, 33),
    crusts: CRUSTS,
  },
  {
    id: '31',
    name: 'Cheddar',
    description: 'Frango com cheddar derretido',
    price: 51.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Cheddar_19_11zon.webp',
    category: 'frango',
    sizes: pizzaSizes(51, 33),
    crusts: CRUSTS,
  },
  {
    id: '32',
    name: 'Carijó',
    description: 'Frango caipira com temperos',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Carijó_14.webp',
    category: 'frango',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },

  // ===================== LEGUMES =====================
  {
    id: '33',
    name: 'Brócolis',
    description: 'Brócolis com mussarela e orégano',
    price: 48.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Brócolis_10.webp',
    category: 'legumes',
    sizes: pizzaSizes(48, 31),
    crusts: CRUSTS,
  },
  {
    id: '34',
    name: 'Escarola',
    description: 'Escarola refogada com alho',
    price: 48.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Escarola_26_11zon.webp',
    category: 'legumes',
    sizes: pizzaSizes(48, 31),
    crusts: CRUSTS,
  },
  {
    id: '35',
    name: 'Palmito',
    description: 'Palmito com mussarela e orégano',
    price: 50.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Palmito_48_11zon.webp',
    category: 'legumes',
    sizes: pizzaSizes(50, 32),
    crusts: CRUSTS,
  },
  {
    id: '36',
    name: 'Milho Verde',
    description: 'Milho verde com mussarela',
    price: 47.0,
    priceBrotinho: 30.0,
    image: '/images/Pizzas/Milho Verde_39_11zon.webp',
    category: 'legumes',
    sizes: pizzaSizes(47, 30),
    crusts: CRUSTS,
  },
  {
    id: '37',
    name: 'Vegetariana',
    description: 'Mix de legumes frescos com mussarela',
    price: 50.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Vegetariana_59_11zon.webp',
    category: 'legumes',
    sizes: pizzaSizes(50, 31),
    crusts: CRUSTS,
  },

  // ===================== PRESUNTO =====================
  {
    id: '38',
    name: 'Portuguesa',
    description: 'Presunto, ovos, cebola, azeitonas, ervilha e mussarela',
    price: 52.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Portuguesa_51_11zon.webp',
    category: 'presunto',
    sizes: pizzaSizes(52, 33),
    crusts: CRUSTS,
  },
  {
    id: '39',
    name: 'Paris',
    description: 'Presunto parisiense com mussarela',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Paris_49_11zon.webp',
    category: 'presunto',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },
  {
    id: '40',
    name: 'Misto',
    description: 'Presunto e mussarela',
    price: 43.0,
    priceBrotinho: 28.0,
    image: '/images/Pizzas/Misto_40_11zon.webp',
    category: 'presunto',
    sizes: pizzaSizes(43, 28),
    crusts: CRUSTS,
  },
  {
    id: '41',
    name: 'Bauru',
    description: 'Presunto, tomate e mussarela',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Bauru_6_11zon.webp',
    category: 'presunto',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },
  {
    id: '42',
    name: 'Itália',
    description: 'Presunto italiano com mussarela e orégano',
    price: 50.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Itália_31.webp',
    category: 'presunto',
    sizes: pizzaSizes(50, 32),
    crusts: CRUSTS,
  },

  // ===================== FRUTOS DO MAR =====================
  {
    id: '43',
    name: 'Atum I',
    description: 'Atum com cebola e mussarela',
    price: 49.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Atum I_1_11zon.webp',
    category: 'frutos-do-mar',
    sizes: pizzaSizes(49, 31),
    crusts: CRUSTS,
  },
  {
    id: '44',
    name: 'Atum II',
    description: 'Atum com catupiry e cebola',
    price: 52.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Atum II_2_11zon.webp',
    category: 'frutos-do-mar',
    sizes: pizzaSizes(52, 32),
    crusts: CRUSTS,
  },
  {
    id: '45',
    name: 'Do Chefe',
    description: 'Frutos do mar selecionados pelo chefe',
    price: 53.0,
    priceBrotinho: 35.0,
    image: '/images/Pizzas/Do Chefe_24_11zon.webp',
    category: 'frutos-do-mar',
    sizes: pizzaSizes(53, 35),
    crusts: CRUSTS,
  },
  {
    id: '46',
    name: 'Ubatuba',
    description: 'Frutos do mar estilo litoral',
    price: 53.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Ubatuba_58_11zon.webp',
    category: 'frutos-do-mar',
    sizes: pizzaSizes(53, 33),
    crusts: CRUSTS,
  },

  // ===================== ESPECIAIS =====================
  {
    id: '47',
    name: 'Salame',
    description: 'Salame italiano com mussarela',
    price: 53.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Salame_55_11zon.webp',
    category: 'especiais',
    sizes: pizzaSizes(53, 33),
    crusts: CRUSTS,
  },
  {
    id: '48',
    name: 'Pepperoni',
    description: 'Pepperoni com mussarela e orégano',
    price: 53.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Pepperoni_50_11zon.webp',
    category: 'especiais',
    sizes: pizzaSizes(53, 33),
    crusts: CRUSTS,
  },
  {
    id: '49',
    name: 'Maluca',
    description: 'Combinação especial da casa',
    price: 52.0,
    priceBrotinho: 33.0,
    image: '/images/Pizzas/Maluca_36_11zon.webp',
    category: 'especiais',
    sizes: pizzaSizes(52, 33),
    crusts: CRUSTS,
  },
  {
    id: '50',
    name: 'Lobo',
    description: 'Exclusiva da Pizzaria Lobo',
    price: 50.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Lobo_33_11zon.webp',
    category: 'especiais',
    sizes: pizzaSizes(50, 32),
    crusts: CRUSTS,
  },
  {
    id: '51',
    name: 'Camarão I',
    description: 'Camarão com mussarela e catupiry',
    price: 65.0,
    priceBrotinho: 41.0,
    image: '/images/Pizzas/Camarão I_12.webp',
    category: 'especiais',
    sizes: pizzaSizes(65, 41),
    crusts: CRUSTS,
  },
  {
    id: '52',
    name: 'Camarão II',
    description: 'Camarão com cheddar e catupiry',
    price: 65.0,
    priceBrotinho: 41.0,
    image: '/images/Pizzas/Camarão II_13.webp',
    category: 'especiais',
    sizes: pizzaSizes(65, 41),
    crusts: CRUSTS,
  },

  // ===================== DOCES =====================
  {
    id: '53',
    name: 'Chocolate I',
    description: 'Chocolate ao leite com granulado',
    price: 49.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Chocolate I_20_11zon.webp',
    category: 'doces',
    sizes: pizzaSizes(49, 32),
    crusts: CRUSTS,
  },
  {
    id: '54',
    name: 'Chocolate II',
    description: 'Chocolate branco com morango',
    price: 49.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/Chocolate II_21_11zon.webp',
    category: 'doces',
    sizes: pizzaSizes(49, 32),
    crusts: CRUSTS,
  },
  {
    id: '55',
    name: 'M&Ms',
    description: 'Chocolate com confetes M&Ms',
    price: 50.0,
    priceBrotinho: 32.0,
    image: '/images/Pizzas/M&Ms_35_11zon.webp',
    category: 'doces',
    sizes: pizzaSizes(50, 32),
    crusts: CRUSTS,
  },
  {
    id: '56',
    name: 'Romeu e Julieta',
    description: 'Goiabada cascão com queijo minas',
    price: 43.0,
    priceBrotinho: 28.0,
    image: '/images/Pizzas/Romeu e Julieta_54_11zon.webp',
    category: 'doces',
    sizes: pizzaSizes(43, 28),
    crusts: CRUSTS,
  },
  {
    id: '57',
    name: 'Nutella I',
    description: 'Creme de avelã Nutella',
    price: 53.0,
    priceBrotinho: 34.0,
    image: '/images/Pizzas/Nutella I_45_11zon.webp',
    category: 'doces',
    sizes: pizzaSizes(53, 34),
    crusts: CRUSTS,
  },
  {
    id: '58',
    name: 'Nutella II',
    description: 'Nutella com morango e leite condensado',
    price: 53.0,
    priceBrotinho: 34.0,
    image: '/images/Pizzas/Nutella II_46_11zon.webp',
    category: 'doces',
    sizes: pizzaSizes(53, 34),
    crusts: CRUSTS,
  },
  {
    id: '59',
    name: 'Prestígio',
    description: 'Chocolate com coco ralado',
    price: 48.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Prestígio_52.webp',
    category: 'doces',
    sizes: pizzaSizes(48, 31),
    crusts: CRUSTS,
  },
  {
    id: '60',
    name: 'Brigadeiro',
    description: 'Brigadeiro cremoso com granulado',
    price: 48.0,
    priceBrotinho: 31.0,
    image: '/images/Pizzas/Brigadeiro_9_11zon.webp',
    category: 'doces',
    sizes: pizzaSizes(48, 31),
    crusts: CRUSTS,
  },

  // ===================== BATATAS =====================
  {
    id: 'BAT001',
    name: 'Batata Simples P',
    description: 'Acompanha ketchup e maionese',
    price: 10.0,
    image: '/images/Batata/batata simples p_4_11zon.webp',
    category: 'batatas',
  },
  {
    id: 'BAT002',
    name: 'Batata Simples G',
    description: 'Acompanha ketchup e maionese',
    price: 21.0,
    image: '/images/Batata/batata simples g_3_11zon.webp',
    category: 'batatas',
  },
  {
    id: 'BAT003',
    name: 'Batata Completa P',
    description: 'Acompanha cheddar e bacon',
    price: 12.0,
    image: '/images/Batata/batata completa p_2_11zon.webp',
    category: 'batatas',
  },
  {
    id: 'BAT004',
    name: 'Batata Completa G',
    description: 'Acompanha cheddar e bacon',
    price: 26.0,
    image: '/images/Batata/batata completa g_1_11zon.webp',
    category: 'batatas',
  },

  // ===================== PASTÉIS =====================
  {
    id: 'PAS001',
    name: 'Pastel de Carne',
    description: 'Carne moída temperada',
    price: 10.0,
    image: '/images/Pasteis/carne_5_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS002',
    name: 'Pastel de Calabresa',
    description: 'Calabresa fatiada',
    price: 10.0,
    image: '/images/Pasteis/calabresa_3_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS003',
    name: 'Pastel de Frango',
    description: 'Frango desfiado temperado',
    price: 10.0,
    image: '/images/Pasteis/frango_8_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS004',
    name: 'Pastel de Queijo',
    description: 'Queijo mussarela derretido',
    price: 10.0,
    image: '/images/Pasteis/queijo_11_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS005',
    name: 'Pastel de Carne com Queijo',
    description: 'Carne moída com mussarela',
    price: 11.0,
    image: '/images/Pasteis/carne com queijo_4_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS006',
    name: 'Pastel de Calabresa com Queijo',
    description: 'Calabresa com mussarela',
    price: 11.0,
    image: '/images/Pasteis/calabresa com queijo_2_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS007',
    name: 'Pastel de Frango com Queijo',
    description: 'Frango desfiado com mussarela',
    price: 11.0,
    image: '/images/Pasteis/frango com queijo_6_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS008',
    name: 'Pastel de Frango com Requeijão',
    description: 'Frango desfiado com requeijão cremoso',
    price: 11.0,
    image: '/images/Pasteis/frango com requeijão_7.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS009',
    name: 'Pastel Misto',
    description: 'Presunto e mussarela',
    price: 11.0,
    image: '/images/Pasteis/misto_9_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS010',
    name: 'Pastel Bauru',
    description: 'Presunto, tomate e mussarela',
    price: 11.0,
    image: '/images/Pasteis/bauru_1_11zon.webp',
    category: 'pasteis',
  },
  {
    id: 'PAS011',
    name: 'Pastel de Pizza',
    description: 'Recheio sabor pizza',
    price: 11.0,
    image: '/images/Pasteis/pizza_10_11zon.webp',
    category: 'pasteis',
  },

  // ===================== BEBIDAS =====================
  {
    id: 'BEB001',
    name: 'Coca-Cola 350 ml',
    description: 'Refrigerante de cola',
    price: 6.0,
    image: '/images/Bebidas/lata coca cola_7_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB002',
    name: 'Guaraná Antarctica 350 ml',
    description: 'Refrigerante de guaraná',
    price: 6.0,
    image: '/images/Bebidas/lata guaraná_8.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB003',
    name: 'Sukita Uva 350 ml',
    description: 'Refrigerante sabor uva',
    price: 6.0,
    image: '/images/Bebidas/lata sukita uva_10_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB004',
    name: 'Sukita Laranja 350 ml',
    description: 'Refrigerante sabor laranja',
    price: 6.0,
    image: '/images/Bebidas/lata sukita laranja_9_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB005',
    name: 'Coca-Cola 1 Litro',
    description: 'Refrigerante de cola 1 litro',
    price: 10.0,
    image: '/images/Bebidas/coca cola 1 litros_1_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB006',
    name: 'Coca-Cola Zero 1 Litro',
    description: 'Refrigerante de cola zero 1 litro',
    price: 10.0,
    image: '/images/Bebidas/coca cola zero_3_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB007',
    name: 'Coca-Cola 2 Litros',
    description: 'Refrigerante de cola 2 litros',
    price: 14.0,
    image: '/images/Bebidas/coca cola 2 litros_2_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB008',
    name: 'Dolly Guaraná 2 Litros',
    description: 'Refrigerante de guaraná 2 litros',
    price: 7.0,
    image: '/images/Bebidas/dolly guaraná 2 litros_6.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB009',
    name: 'Tiss Tubaina 600 ml',
    description: 'Refrigerante sabor tubaina',
    price: 6.0,
    image: '/images/Bebidas/tiss tubaína_15.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB010',
    name: 'Tiss Guaraná 600 ml',
    description: 'Refrigerante de guaraná',
    price: 6.0,
    image: '/images/Bebidas/tiss guaraná_14.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB011',
    name: 'Sukita Laranja 2 Litros',
    description: 'Refrigerante sabor laranja 2 litros',
    price: 11.0,
    image: '/images/Bebidas/sukita laranja 2 litros_12_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB012',
    name: 'Sukita Uva 2 Litros',
    description: 'Refrigerante sabor uva 2 litros',
    price: 11.0,
    image: '/images/Bebidas/sukita 2 litros_11_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB013',
    name: 'Sukita Tubaina 2 Litros',
    description: 'Refrigerante sabor tubaina 2 litros',
    price: 11.0,
    image: '/images/Bebidas/sukita tubaina_13_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB014',
    name: 'Suco Del Valle Uva 1 Litro',
    description: 'Suco de uva 1 litro',
    price: 11.0,
    image: '/images/Bebidas/dellvale uva_5_11zon.webp',
    category: 'bebidas',
  },
  {
    id: 'BEB015',
    name: 'Suco Del Valle Frutas Cítricas 1 Litro',
    description: 'Suco de frutas cítricas 1 litro',
    price: 11.0,
    image: '/images/Bebidas/dellvale frutas cítricas_4.webp',
    category: 'bebidas',
  },
];
